export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const SET_RESTAURANT = "SET_RESTAURANT";
export const SET_NEAREST_BEACON_DATA = "SET_NEAREST_BEACON_DATA";
export const SET_NEAR_BEACONS_DATA = "SET_NEAR_BEACONS_DATA";
export const SET_NEAREST_BEACON_KEYS = "SET_NEAREST_BEACON_KEYS";
export const SET_LOCATION = "SET_LOCATION";
export const SET_MENU = "SET_MENU";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_ORDERS = "SET_ORDERS";
export const SET_RESTAURANT_SEARCH_RESULTS = "SET_RESTAURANT_SEARCH_RESULTS";
export const RESET_RESTAURANT_DATA = "RESET_RESTAURANT_DATA";
export const SET_HISTORY = "SET_HISTORY";
export const SET_NEAR_RESTAURANTS = "SET_NEAR_RESTAURANTS";
export const RESET_BEACONS_DATA = "RESET_BEACONS_DATA";
export const SET_POSTS = "SET_POSTS";

export const SET_RESTAURANT_ADMIN = "SET_RESTAURANT_ADMIN";
export const SET_LOCATION_ADMIN = "SET_LOCATION_ADMIN";
export const SET_MENU_ADMIN = "SET_MENU_ADMIN";
export const SET_CATEGORIES_ADMIN = "SET_CATEGORIES_ADMIN";
export const SET_ORDERS_ADMIN = "SET_ORDERS_ADMIN";
export const SET_TABLES = "SET_TABLES";
export const SET_TABLES_ADMIN = "SET_TABLES_ADMIN";


